services:
  vscode_bybit:
    image: docker/dev-environments-go:stable-1
    container_name: vscode_bybit
    labels:
      - dev.orbstack.domains=bybit.local
    entrypoint:
    - sleep
    - infinity
    init: true
    volumes:
    - type: bind
      source: .
      target: /mnt/workspace
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    networks:
      - go_dev

networks:
  go_dev:
    external: true
